name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     # - name: Test
     #   run: |
     #     echo ${{ env.CODO_TOKEN }}

    - name: Check out json ci repo
      uses: actions/checkout@v4
      with:
        repository: SiliconLabsSoftware/aep_ci_tools
        token: ${{ env.CODO_TOKEN }}
      
